target("MyEngineRuntimeLinkProbe")
    set_kind("binary")
    set_default(false)
    add_rules("myengine.module", "copy_runtime_library")
    set_values("myengine.module.root", os.scriptdir())
    set_values("myengine.architecture.role", "probe")
    add_deps("MyEngine.Runtime.API", "MyEngineRuntime")
    set_rundir("$(projectdir)")
target_end()
