#include "Project/SaveGame.h"
#include "Assets/AssetManager.h"
#include <filesystem>
#include <fstream>
#include <cctype>
namespace fs=std::filesystem;namespace{void Err(std::string* error,const std::string& value){if(error)*error=value;}}
bool SaveGame::Resolve(const std::string& slot,std::string& path,std::string* error){fs::path value(slot);if(slot.empty()||value.is_absolute()||value.has_parent_path()||value.extension()!=".json"){Err(error,"save slot must be a filename ending in .json");return false;}for(char ch:slot)if(!(std::isalnum(static_cast<unsigned char>(ch))||ch=='_'||ch=='-'||ch=='.')){Err(error,"save slot contains invalid characters");return false;}fs::path root=AssetManager::Get().GetProjectRoot()/"Saved"/"SaveGames";std::error_code ec;fs::create_directories(root,ec);if(ec){Err(error,"failed to create save directory");return false;}path=(root/value).string();return true;}
nlohmann::json SaveGame::ToJson(const SaveGameData& d){return{{"version",SaveGameData::CurrentVersion},{"checkpoint",d.checkpoint},{"player",d.player},{"collected",d.collected},{"settings",d.settings}};}
bool SaveGame::FromJson(nlohmann::json value,SaveGameData& data,std::string* error){if(!value.is_object()){Err(error,"save root must be an object");return false;}int version=value.value("version",1);if(version<1||version>SaveGameData::CurrentVersion){Err(error,"unsupported save version");return false;}if(version==1){if(!value.contains("settings"))value["settings"]=nlohmann::json::object();value["version"]=2;version=2;}data.version=version;data.checkpoint=value.value("checkpoint",std::string{});data.player=value.value("player",nlohmann::json::object());data.collected=value.value("collected",std::vector<std::string>{});data.settings=value.value("settings",nlohmann::json::object());if(!data.player.is_object()||!data.settings.is_object()){Err(error,"save player/settings must be objects");return false;}return true;}
bool SaveGame::Write(const std::string& slot,const SaveGameData& data,std::string* error){std::string path;if(!Resolve(slot,path,error))return false;const std::string temporary=path+".tmp";try{{std::ofstream out(temporary,std::ios::binary|std::ios::trunc);if(!out){Err(error,"failed to open temporary save");return false;}out<<ToJson(data).dump(2);if(!out){Err(error,"failed to write save");return false;}}std::error_code ec;fs::remove(path,ec);ec.clear();fs::rename(temporary,path,ec);if(ec){fs::remove(temporary);Err(error,"failed to commit save");return false;}return true;}catch(const std::exception& e){Err(error,e.what());fs::remove(temporary);return false;}}
bool SaveGame::Read(const std::string& slot,SaveGameData& data,std::string* error){std::string path;if(!Resolve(slot,path,error))return false;try{std::ifstream in(path,std::ios::binary);if(!in){Err(error,"save does not exist");return false;}nlohmann::json value;in>>value;return FromJson(std::move(value),data,error);}catch(const std::exception& e){Err(error,e.what());return false;}}
bool SaveGame::Exists(const std::string& slot){std::string path;if(!Resolve(slot,path,nullptr))return false;std::error_code ec;return fs::is_regular_file(path,ec)&&!ec;}
bool SaveGame::Remove(const std::string& slot,std::string* error){std::string path;if(!Resolve(slot,path,error))return false;std::error_code ec;bool removed=fs::remove(path,ec);if(ec)Err(error,ec.message());return removed&&!ec;}
